### ISSUE TITLE
[bugfix] 도넛 차트 퍼센테이지 100% 계산 문제

### ISSUE THREAD

**Issue by KangyeolLee** [woowa-techcamp-2021/cashbook-18#80]
- 반올림하여 퍼센트 값을 전달하고 있는데 일부 경우 100%가 넘는 경우 발생
- 또는 0% 수치가 기록되는 경우 발생

위 두 가지 경우에 대한 대책 마련이 필요합니다

**Comment by eun-seong** [comment]
통계학적으로 백분율을 100으로 만드는 방법은 없다고 해요 😂

**Comment by KangyeolLee** [comment]
> 통계학적으로 정제된 백분율의 합을 100으로 만드는 방법은 없다고 해요 😂

그래서 오차범위를 넣는 것으로 해결을 보았습니다(?)
