### ISSUE TITLE
[feature] 데이터 없을 시 보여줄 페이지 제작

### ISSUE THREAD

**Issue by KangyeolLee** [woowa-techcamp-2021/cashbook-18#86]
- 해당 년/월/일에 일치하는 데이터가 없는 경우 보여줄 페이지가 필요합니다..!
- PS) 디자인 어케하죱?

**Comment by eun-seong** [comment]
1. 글쓰기 버튼을 가리키는 화살표 메세지 같은 엘리먼트 생성해서 애니메이션으로 왔따갔따?
2. `첫 히스토리를 작성해보세요!` 문구를 pretty하게..

**Comment by KangyeolLee** [comment]
> 1. 글쓰기 버튼을 가리키는 화살표 메세지 같은 엘리먼트 생성해서 애니메이션으로 왔따갔따?
> 2. `첫 히스토리를 작성해보세요!` 문구를 pretty하게..

ㅋㅋㅋ 디자인 끝내고 머지하는 시점에서 코멘트를 확인하네요 제성..
